/* ========================================================= JAVASCRIPT — CALENDÁRIO / FERIADOS / ALERTAS ========================================================= */
let selectedCalendarDay=null;
function changeMonth(x){changeReferenceMonth(x)}
function expenseDueInMonth(e,y,m){const key=`${y}-${String(m+1).padStart(2,'0')}`;if(expMonth(e,key)<=0)return null;return dueDateForMonth(e,key)?.getDate()||null}
function nationalHolidays(y){return [{date:`${y}-01-01`,name:'Confraternização Universal'},{date:`${y}-04-21`,name:'Tiradentes'},{date:`${y}-05-01`,name:'Dia do Trabalho'},{date:`${y}-09-07`,name:'Independência do Brasil'},{date:`${y}-10-12`,name:'Nossa Senhora Aparecida'},{date:`${y}-11-02`,name:'Finados'},{date:`${y}-11-15`,name:'Proclamação da República'},{date:`${y}-11-20`,name:'Dia Nacional de Zumbi e da Consciência Negra'},{date:`${y}-12-25`,name:'Natal'}]}
function calendarEventsForDate(dateStr){const key=dateStr.slice(0,7),d=Number(dateStr.slice(8,10)),[y,m]=key.split('-').map(Number),events=[];data.expenses.forEach(e=>{if(expenseDueInMonth(e,y,m-1)===d){const st=expenseState(e,key);events.push({type:'expense',name:e.name,value:expMonth(e,key),status:st})}});data.incomeSources.forEach(r=>{const days=new Date(y,m,0).getDate();if(Math.min(days,Math.max(1,Number(r.payDay)||5))===d){const rec=incomeRecord(r,key);events.push({type:'income',name:r.title||'Renda',value:rec?.received?rec.received:incomeExpected(r),status:rec?.received?'recebido':'previsto'})}});const hol=[...nationalHolidays(y),...(data.profile.holidays||[])].filter(h=>h.date===dateStr);hol.forEach(h=>events.push({type:'holiday',name:h.name,status:h.type||'nacional'}));(data.profile.va?.transactions||[]).filter(t=>t.date===dateStr).forEach(t=>events.push({type:'va',name:`VA · ${t.category}`,value:t.amount,status:t.desc||''}));return events}
function renderCalendar(){const y=view.getFullYear(),m=view.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();let h=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="muted cal-weekday">${x}</div>`).join('');const start=(first.getDay()+6)%7;for(let i=0;i<start;i++)h+='<div></div>';for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,events=calendarEventsForDate(date),holiday=events.some(e=>e.type==='holiday'),today=date===new Date().toISOString().slice(0,10);h+=`<button class="day day-v8 ${events.length?'has-events':''} ${holiday?'holiday-day':''} ${today?'today':''}" onclick="selectCalendarDay('${date}')"><b>${d}</b>${events.length?`<span class="cal-indicators">${events.slice(0,4).map(e=>`<i class="dot ${e.type}"></i>`).join('')}<small>${events.length}</small></span>`:''}</button>`}cal.innerHTML=h;calTitle.textContent=first.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});if(selectedCalendarDay?.slice(0,7)!==selectedMonthKey())selectedCalendarDay=`${selectedMonthKey()}-01`;selectCalendarDay(selectedCalendarDay||`${selectedMonthKey()}-01`,false)}
function selectCalendarDay(dateStr,rerender=false){selectedCalendarDay=dateStr;const title=document.getElementById('calendarDayTitle'),el=document.getElementById('calendarDayDetails'),events=calendarEventsForDate(dateStr);if(title)title.textContent=new Date(dateStr+'T12:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});if(el)el.innerHTML=events.length?events.map(ev=>`<div class="calendar-event-row ${ev.type}"><span><b>${esc(ev.name)}</b><small>${esc(ev.status||'')}</small></span>${ev.value!=null?`<strong>${ev.type==='expense'||ev.type==='va'?'− ':'+ '}${money(ev.value)}</strong>`:''}</div>`).join(''):'<div class="empty-state compact-empty"><h3>Nada registrado neste dia</h3><p>Vencimentos, rendas, VA e feriados aparecem aqui.</p></div>';if(rerender)renderCalendar()}
function saveHoliday(){const date=holidayDate.value,name=holidayName.value.trim(),type=holidayType.value;if(!date||!name)return toast('Informe a data e o nome.',true);data.profile.holidays=data.profile.holidays||[];data.profile.holidays.push({id:id(),date,name,type,state:data.profile.state||'',city:data.profile.city||''});logActivity('calendar','Data adicionada',name);save();closeM('holiday');selectedCalendarDay=date;toast('✓ Data adicionada ao calendário')}
function nextExpenseDue(e,from=new Date()){from=new Date(from);from.setHours(12,0,0,0);for(let i=0;i<14;i++){const dt=new Date(from.getFullYear(),from.getMonth()+i,1,12),key=mkey(dt),due=dueDateForMonth(e,key);if(due&&due>=from&&expMonth(e,key)>0)return due}return null}
function renderAlerts(){const t=new Date();t.setHours(12,0,0,0),a=[];data.expenses.forEach(e=>{const d=nextExpenseDue(e,t);if(!d)return;const dif=Math.round((d-t)/864e5),key=mkey(d),st=expenseState(e,key);if(st==='paid')return;if(dif<0)a.push('🔴 '+e.name+' — atrasado há '+Math.abs(dif)+' dia(s)');else if(dif<=3)a.push('🟡 '+e.name+' — vence '+(dif?'em '+dif+' dia(s)':'hoje'))});const carry=arrearsTotal(selectedMonthKey());if(carry>0)a.unshift('🔴 Pendências anteriores acumuladas: '+money(carry));alertsList.innerHTML=a.length?a.map(x=>`<div class="alert">${esc(x)}</div>`).join(''):'<div class="empty-state compact-empty"><h3>Sem alertas importantes</h3><p>Vencimentos próximos, pendências e limites aparecem aqui.</p></div>';const r=data.incomeSources[0];work.innerHTML=r?`<div class="row"><span>Fechamento</span><b>dia ${r.close||data.profile.closeDay||22}</b></div><div class="row"><span>Pagamento cadastrado</span><b>dia ${r.payDay||5}</b></div><p class="muted">As datas são referências cadastradas por você e podem variar.</p>`:'<div class="empty-state compact-empty"><h3>Sem renda de trabalho</h3><p>Cadastre uma renda para acompanhar datas relacionadas ao pagamento.</p></div>'}
