/* ========================================================= JAVASCRIPT — GASTOS / PIX CRÉDITO / PAGAMENTOS ========================================================= */
let editingExpenseId=null;
function openM(x){document.getElementById('m'+x[0].toUpperCase()+x.slice(1))?.classList.add('show')}
function closeM(x){document.getElementById('m'+x[0].toUpperCase()+x.slice(1))?.classList.remove('show')}
function resetExpenseForm(){editingExpenseId=null;expenseModalTitle.textContent='Adicionar gasto';expenseSaveBtn.textContent='Salvar gasto';eName.value='';eVal.value='';eType.value='single';eResponsibility.value='mine';eMethod.value='PIX';eParts.value=1;eDebtTotal.value='';eDebtParts.value=1;eCurrentPart.value='';eMyShare.value='';eOthersShare.value='';ePixSent.value='';ePixTotal.value='';ePixParts.value=1;ePixExtra.value='';ePixPct.value='';const today=new Date();eDate.value=today.toISOString().slice(0,10);eDue.value=eDate.value;expenseUI()}
function openExpenseEditor(x){const e=data.expenses.find(v=>v.id===x);if(!e)return;editingExpenseId=x;expenseModalTitle.textContent='Editar gasto';expenseSaveBtn.textContent='Salvar alterações';eName.value=e.name;eCat.value=e.category;eType.value=e.type;eResponsibility.value=e.responsibility||'mine';eMethod.value=e.method||'PIX';eDate.value=e.date||'';eDue.value=e.due||e.date||'';eParts.value=e.parts||1;eVal.value=e.responsibility==='shared'?'':money(e.value);eDebtTotal.value=e.debtTotal?money(e.debtTotal):'';eDebtParts.value=e.debtParts||e.parts||1;eCurrentPart.value=e.currentPart?money(e.currentPart):'';eMyShare.value=e.myShare?money(e.myShare):'';eOthersShare.value=e.currentPart&&e.myShare?money(Math.max(0,e.currentPart-e.myShare)):'';ePixSent.value=e.pixCredit?.sent?money(e.pixCredit.sent):'';ePixTotal.value=e.pixCredit?.total?money(e.pixCredit.total):'';ePixParts.value=e.pixCredit?.parts||e.parts||1;updatePixPreview();expenseUI();openM('expense')}
function updatePixPreview(){const sent=n(ePixSent?.value),total=n(ePixTotal?.value),extra=Math.max(0,total-sent),pct=sent>0?extra/sent*100:0;if(ePixExtra)ePixExtra.value=total?money(extra):'';if(ePixPct)ePixPct.value=sent&&total?pct.toFixed(2).replace('.',',')+'%':''}
function expenseUI(){const shared=eResponsibility.value==='shared',pix=eMethod.value==='PIX Crédito';partsWrap.style.display=shared||(!pix&&eType.value!=='single')?'grid':'none';normalValueWrap.style.display=shared||pix?'none':'grid';sharedDebtWrap.style.display=shared?'block':'none';pixCreditWrap.style.display=!shared&&pix?'block':'none';if(shared){eType.value='installment';eDebtParts.value=eDebtParts.value||eParts.value||1;eParts.value=eDebtParts.value}if(pix){const pp=Math.min(10,Math.max(1,Number(ePixParts.value)||1));eType.value=pp>1?'installment':'single'}if(document.activeElement!==eOthersShare)eOthersShare.value=(n(eCurrentPart.value)||0)>0?money(Math.max(0,n(eCurrentPart.value)-n(eMyShare.value))):'';updatePixPreview()}
eCurrentPart.addEventListener('input',expenseUI);eMyShare.addEventListener('input',expenseUI);ePixSent?.addEventListener('input',updatePixPreview);ePixTotal?.addEventListener('input',updatePixPreview);ePixParts?.addEventListener('input',expenseUI);
function saveExpense(){let name=eName.value.trim(),type=eType.value,shared=eResponsibility.value==='shared',e;if(!name)return toast('Informe o nome.',true);const common={id:editingExpenseId||id(),name,category:eCat.value,method:eMethod.value,date:eDate.value||new Date().toISOString().slice(0,10),due:eDue.value||eDate.value,trackingStartKey:editingExpenseId?(data.expenses.find(x=>x.id===editingExpenseId)?.trackingStartKey||selectedMonthKey()):selectedMonthKey()};
  if(shared){let debt=n(eDebtTotal.value),parts=Number(eDebtParts.value)||1,current=n(eCurrentPart.value),mine=n(eMyShare.value);if(debt<=0||current<=0||mine<=0)return toast('Preencha dívida, parcela atual e quanto você paga.',true);if(mine>current)return toast('Sua parte não pode ser maior que a parcela.',true);e={...common,value:debt,type:'installment',parts,debtTotal:debt,debtParts:parts,currentPart:current,myShare:mine,responsibility:'shared'}}
  else if(eMethod.value==='PIX Crédito'){const sent=n(ePixSent.value),total=n(ePixTotal.value),parts=Math.min(10,Math.max(1,Number(ePixParts.value)||1));if(sent<=0||total<=0)return toast('Informe o valor enviado e o total cobrado no PIX Crédito.',true);if(total<sent)return toast('O total cobrado não pode ser menor que o valor enviado.',true);e={...common,value:total,type:parts>1?'installment':'single',parts,responsibility:'mine',pixCredit:{sent,total,parts,extra:total-sent,pct:sent?(total-sent)/sent*100:0}}}
  else{let value=n(eVal.value);if(value<=0)return toast('Informe o valor.',true);e={...common,value,type,responsibility:'mine'};if(type!=='single')e.parts=Number(eParts.value)||1}
  if(editingExpenseId){const idx=data.expenses.findIndex(v=>v.id===editingExpenseId);if(idx>=0)data.expenses[idx]=e;logActivity('expense','Gasto atualizado',name,expMonth(e))}else{data.expenses.push(e);logActivity('expense','Novo gasto',name,expMonth(e))}save();closeM('expense');toast(editingExpenseId?'✓ Gasto atualizado':'✓ Gasto salvo');editingExpenseId=null;go('expenses')}
function delExpense(x){const e=data.expenses.find(v=>v.id===x);if(confirm('Excluir gasto e seu histórico de pagamento?')){if(e)logActivity('expense','Gasto excluído',e.name,expMonth(e));data.expenses=data.expenses.filter(e=>e.id!==x);delete data.expenseStatus[x];save()}}
function expenseTypeLabel(e){if(e.method==='PIX Crédito')return e.pixCredit?.parts>1?`PIX Crédito · ${e.pixCredit.parts}x`:'PIX Crédito';if(e.responsibility==='shared')return'Dívida compartilhada';if(e.type==='single')return'Única';if(e.type==='installment')return`${e.parts||1}x`;if(e.type==='indefinite')return'Mensal';return'Mensal c/ prazo'}
function expenseProgressHtml(e,key=selectedMonthKey()){if(typeof installmentNumber!=='function')return'';const [y,m]=key.split('-').map(Number),prog=installmentNumber(e,new Date(y,m-1,1,12));if(!prog||prog.total<=1)return'';return `<div class="installment-progress"><div><span>Parcela ${prog.current} de ${prog.total}</span><span>${Math.round(prog.pct)}%</span></div><div class="progress mini-progress"><span style="width:${prog.pct}%"></span></div></div>`}
function paymentBadge(e,key){const st=expenseState(e,key);return `<button class="pay-check ${st}" onclick="setExpensePaid('${e.id}','${key}',${st!=='paid'})">${st==='paid'?'✓ Pago':st==='overdue'?'! Atrasado':'○ Pendente'}</button>`}
function pixCreditDetail(e){if(e.method!=='PIX Crédito'||!e.pixCredit)return'';return `<div class="pix-credit-detail"><span>Enviado: ${money(e.pixCredit.sent)}</span><span>Total: ${money(e.pixCredit.total)}</span><span>Custo extra: <b>${money(e.pixCredit.extra)}</b> (${Number(e.pixCredit.pct||0).toFixed(2).replace('.',',')}%)</span></div>`}
function renderExpenses(){const el=document.getElementById('expenseList');if(!el)return;const key=selectedMonthKey(),active=data.expenses.filter(e=>expMonth(e,key)>0),stats=monthlyExpenseStats(key),summary=document.getElementById('expenseSummary');if(summary)summary.innerHTML=`<div><small class="muted">PREVISTO</small><b>${money(stats.expected)}</b></div><div><small class="muted">PAGO</small><b class="ok">${money(stats.paid)}</b></div><div><small class="muted">PENDENTE + ANTERIOR</small><b class="bad">${money(stats.pending+stats.arrears)}</b></div>`;
  if(!active.length){el.innerHTML='<div class="empty-state"><div class="empty-icon">💸</div><h3>Nenhum gasto nesta competência</h3><p>Gastos únicos de outros meses não aparecem aqui. Mensalidades e parcelas surgem automaticamente quando estiverem ativas.</p><button class="btn primary" onclick="resetExpenseForm();openM(\'expense\')">+ Adicionar gasto</button></div>';return}
  const arrears=arrearsEntries(key);let arrearsHtml=arrears.length?`<div class="arrears-box"><b>Pendências trazidas de meses anteriores</b>${arrears.map(a=>`<div class="row"><span>${esc(a.e.name)} · ${monthLabel(a.key)}</span><b class="bad">${money(a.amount)}</b></div>`).join('')}</div>`:'';
  const cards=active.map(e=>{const impact=expMonth(e,key),detail=e.responsibility==='shared'?`Você paga ${money(e.myShare)} de ${money(e.currentPart)}`:esc(e.method||'');return `<article class="expense-mobile-card"><div class="expense-card-head"><div><b>${esc(e.name)}</b><small>${esc(e.category)} · ${expenseTypeLabel(e)}</small></div><strong>${money(impact)}</strong></div>${expenseProgressHtml(e,key)}${pixCreditDetail(e)}<div class="expense-card-foot"><span>${dueDateForMonth(e,key)?.toLocaleDateString('pt-BR')||'Sem vencimento'}</span><span>${detail}</span></div><div class="actions">${paymentBadge(e,key)}<button class="btn sm" onclick="openExpenseEditor('${e.id}')">Editar</button><button class="btn sm danger" onclick="delExpense('${e.id}')">Excluir</button></div></article>`}).join('');
  el.innerHTML=arrearsHtml+'<div class="expense-cards-mobile force-cards">'+cards+'</div>'}
