/* ========================================================= JAVASCRIPT — RENDAS / HISTÓRICO POR COMPETÊNCIA ========================================================= */
let incomeMode='simple',editingIncomeId=null;
function switchIncomeMode(mode='simple'){incomeMode=mode==='detailed'?'detailed':'simple';document.getElementById('incomeSimpleTab')?.classList.toggle('active',incomeMode==='simple');document.getElementById('incomeDetailedTab')?.classList.toggle('active',incomeMode==='detailed');document.getElementById('incomeSimplePanel')?.classList.toggle('active',incomeMode==='simple');document.getElementById('incomeDetailedPanel')?.classList.toggle('active',incomeMode==='detailed')}
function resetIncomeForm(){editingIncomeId=null;switchIncomeMode('simple');const defaults={iSimpleTitle:'',iSimpleNet:'',iSimplePayDay:'5',iSimpleCompany:'',iTitle:'',iCompany:'',iMonthly:'',iNetReal:'',iDaily:'',iDays:'22',iBase:'',iInsManual:'',iClose:'22',iPayDay:'5',iVaDay:'',iVtDay:'',iVa:'',iVt:'',iTrips:'2'};Object.entries(defaults).forEach(([id,val])=>{const el=document.getElementById(id);if(el)el.value=val});if(iType)iType.value='salary';if(iIns)iIns.value='0';if(iInsBase)iInsBase.value='salary'}
function openIncomeModal(){resetIncomeForm();openM('income')}
function openIncomeEditor(uid){const r=data.incomeSources.find(x=>x.id===uid);if(!r)return;editingIncomeId=uid;switchIncomeMode(r.mode||'simple');if(r.mode==='simple'){iSimpleTitle.value=r.title||'';iSimpleNet.value=money(incomeExpected(r));iSimplePayDay.value=r.payDay||5;iSimpleCompany.value=r.company||''}else{iTitle.value=r.title||'';iType.value=r.type||'salary';iCompany.value=r.company||'';iMonthly.value=r.monthly?money(r.monthly):'';iNetReal.value=incomeExpected(r)?money(incomeExpected(r)):'';iDaily.value=r.daily?money(r.daily):'';iDays.value=r.days||22;iIns.value=r.ins||'0';iInsBase.value=r.insBase||'salary';iBase.value=r.baseManual?money(r.baseManual):'';iInsManual.value=r.insManual?money(r.insManual):'';iClose.value=r.close||22;iPayDay.value=r.payDay||5;iVaDay.value=r.vaDay||'';iVtDay.value=r.vtDay||'';iVa.value=r.va||'';iVt.value=r.vt||'';iTrips.value=r.trips||2}openM('income')}
function saveIncome(){let item;if(incomeMode==='simple'){const title=String(iSimpleTitle?.value||'').trim(),estimated=n(iSimpleNet?.value),company=String(iSimpleCompany?.value||'').trim(),payDay=Math.min(31,Math.max(1,Number(iSimplePayDay?.value)||5));if(!title||estimated<=0)return toast('Informe o nome da renda e o valor líquido estimado.',true);item={mode:'simple',title,type:'salary',company,monthly:0,netReal:estimated,estimatedNet:estimated,daily:0,days:22,ins:'0',insBase:'salary',baseManual:0,insManual:0,close:Number(data.profile?.closeDay)||22,payDay,vaDay:0,vtDay:0,va:0,vt:0,trips:2}}
  else{const title=iTitle.value.trim(),monthly=n(iMonthly.value),daily=n(iDaily.value),estimated=n(iNetReal.value);if(!title||(!monthly&&!daily&&!estimated))return toast('Informe o título e pelo menos um valor.',true);item={mode:'detailed',title,type:iType.value,company:iCompany.value,monthly,netReal:estimated,estimatedNet:estimated,daily,days:Number(iDays.value)||22,ins:iIns.value,insBase:iInsBase.value,baseManual:n(iBase.value),insManual:n(iInsManual.value),close:Number(iClose.value)||22,payDay:Number(iPayDay.value)||5,vaDay:Number(iVaDay.value)||0,vtDay:Number(iVtDay.value)||0,va:n(iVa.value),vt:n(iVt.value),trips:Number(iTrips.value)||2}}
  if(editingIncomeId){const old=data.incomeSources.find(x=>x.id===editingIncomeId),idx=data.incomeSources.findIndex(x=>x.id===editingIncomeId);item.id=editingIncomeId;item.monthlyRecords=old?.monthlyRecords||{};data.incomeSources[idx]=item;logActivity('income','Renda atualizada',item.title,incomeExpected(item))}else{item.id=id();item.monthlyRecords={};data.incomeSources.push(item);logActivity('income','Nova fonte de renda',item.title,incomeExpected(item))}save();closeM('income');toast(editingIncomeId?'✓ Renda atualizada':'✓ Renda salva');editingIncomeId=null;go('income')}
function registerIncomeReceived(uid,key=selectedMonthKey()){const r=data.incomeSources.find(x=>x.id===uid);if(!r)return;const current=n(r.monthlyRecords?.[key]?.received);const val=prompt(`Quanto realmente entrou de “${r.title}” em ${monthLabel(key)}?`,current?String(current).replace('.',','):'');if(val===null)return;const amount=n(val);if(amount<=0)return toast('Informe um valor recebido maior que zero.',true);r.monthlyRecords=r.monthlyRecords||{};r.monthlyRecords[key]={received:amount,date:new Date().toISOString().slice(0,10)};logActivity('income','Renda recebida',`${r.title} · ${monthLabel(key)}`,amount);save();toast('✓ Valor recebido registrado')}
function clearIncomeReceived(uid,key=selectedMonthKey()){const r=data.incomeSources.find(x=>x.id===uid);if(!r?.monthlyRecords?.[key])return;if(confirm(`Remover o valor recebido de ${monthLabel(key)}? A fonte de renda continuará cadastrada.`)){delete r.monthlyRecords[key];save()}}
function delIncome(x){const r=data.incomeSources.find(v=>v.id===x);if(confirm('Excluir esta fonte e todo o histórico dela?')){if(r)logActivity('income','Renda excluída',r.title,incomeExpected(r));data.incomeSources=data.incomeSources.filter(r=>r.id!==x);save()}}
function incomeHistoryHtml(r){const rows=Object.entries(r.monthlyRecords||{}).filter(([,v])=>n(v.received)>0).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,8);if(!rows.length)return'<small class="muted">Nenhum mês recebido registrado ainda.</small>';return `<div class="income-history">${rows.map(([k,v])=>`<span><b>${monthLabel(k)}</b><em>${money(v.received)}</em></span>`).join('')}</div>`}
function renderIncome(){const el=document.getElementById('incomeList');if(!el)return;const key=selectedMonthKey(),expected=incomeExpectedTotal(),received=incomeReceivedTotal(key),used=incomeTotal(key),summary=document.getElementById('incomeMonthSummary');if(summary)summary.innerHTML=`<div><small class="muted">ESTIMADO</small><b>${money(expected)}</b></div><div><small class="muted">RECEBIDO</small><b class="ok">${money(received)}</b></div><div><small class="muted">DIFERENÇA</small><b class="${received&&received<expected?'bad':'ok'}">${received?money(received-expected):'Aguardando'}</b></div>`;
  if(!data.incomeSources.length){el.innerHTML='<div class="empty-state"><div class="empty-icon">💰</div><h3>Cadastre sua primeira renda</h3><p>O FinanSee usa sua renda para calcular quanto está comprometido e quanto realmente fica disponível.</p><button class="btn primary" onclick="openIncomeModal()">+ Adicionar renda</button></div>';return}
  el.innerHTML='<div class="income-source-list">'+data.incomeSources.map(r=>{const rec=incomeRecord(r,key),est=incomeExpected(r),actual=n(rec?.received),diff=actual?actual-est:null;return `<article class="income-source-card"><div class="top compact"><div><b>${esc(r.title)}</b><small class="muted">${esc(r.company||r.type||'Renda')} · pagamento dia ${r.payDay||5}</small></div><span class="badge">${r.mode==='simple'?'Simples':'Detalhado'}</span></div><div class="grid three mini-summary"><div><small class="muted">ESTIMADO</small><b>${money(est)}</b></div><div><small class="muted">RECEBIDO EM ${monthLabel(key).toUpperCase()}</small><b class="${actual?'ok':''}">${actual?money(actual):'Não informado'}</b></div><div><small class="muted">DIFERENÇA</small><b class="${diff!=null&&diff<0?'bad':'ok'}">${diff==null?'—':money(diff)}</b></div></div><div class="actions"><button class="btn sm primary" onclick="registerIncomeReceived('${r.id}','${key}')">${actual?'Editar recebido':'Registrar recebido'}</button>${actual?`<button class="btn sm" onclick="clearIncomeReceived('${r.id}','${key}')">Limpar mês</button>`:''}<button class="btn sm" onclick="openIncomeEditor('${r.id}')">Editar fonte</button><button class="btn sm danger" onclick="delIncome('${r.id}')">Excluir</button></div><details class="income-history-details"><summary>Histórico desta renda</summary>${incomeHistoryHtml(r)}</details></article>`}).join('')+'</div>'}
