/* ========================================================= JAVASCRIPT — METAS ========================================================= */
function saveGoal(){let name=gName.value.trim(),target=n(gTarget.value);if(!name||target<=0)return toast('Informe meta e valor.',true);data.goals.push({id:id(),name,target,saved:n(gSaved.value),monthly:n(gMonthly.value),date:gDate.value});logActivity('goal','Nova meta',name,target);save();closeM('goal');toast('✓ Meta salva');go('planning')}
function addGoalDeposit(x){let g=data.goals.find(v=>v.id===x);if(!g)return;let input=document.getElementById('dep_'+x),v=n(input.value);if(v<=0)return toast('Informe um valor para o aporte.',true);g.saved=n(g.saved)+v;input.value='';logActivity('goal','Aporte em meta',g.name,v);save();toast('✓ Aporte contabilizado')}
function delGoal(x){const g=data.goals.find(v=>v.id===x);if(confirm('Excluir esta meta?')){if(g)logActivity('goal','Meta excluída',g.name,g.target);data.goals=data.goals.filter(g=>g.id!==x);save()}}
function renderGoals(){let el=document.getElementById('goals');if(!el)return;let targetTotal=data.goals.reduce((s,g)=>s+n(g.target),0),savedTotal=data.goals.reduce((s,g)=>s+n(g.saved),0);let summary=`<div class="grid three" style="margin-bottom:16px"><div><small class="muted">TOTAL DAS METAS</small><div class="value">${money(targetTotal)}</div></div><div><small class="muted">TOTAL DEPOSITADO</small><div class="value ok">${money(savedTotal)}</div></div><div><small class="muted">TOTAL NO COFRE</small><div class="value">${money(totalVaults())}</div></div></div><div class="row" style="margin-bottom:8px"><span class="muted">Falta juntar nas metas</span><b>${money(Math.max(0,targetTotal-savedTotal))}</b></div>`;el.innerHTML=summary+(data.goals.length?data.goals.map(g=>{let p=Math.min(100,n(g.saved)/Math.max(1,n(g.target))*100);return `<div class="row" style="align-items:flex-start"><div style="width:100%"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>🎯 ${esc(g.name)}</b><span class="badge">${p.toFixed(0)}%</span></div><small>${money(g.saved)} / ${money(g.target)} · ${money(g.monthly)}/mês${g.date?' · até '+new Date(g.date+'T00:00').toLocaleDateString('pt-BR'):''}</small><div class="progress" style="margin-top:7px"><span style="width:${p}%"></span></div><div class="actions" style="margin-top:10px"><input id="dep_${g.id}" placeholder="Aporte" style="max-width:130px;padding:7px;border:1px solid var(--line);border-radius:9px;background:var(--card);color:var(--text)"><button class="btn sm primary" onclick="addGoalDeposit('${g.id}')">+ Depositar</button><button class="btn sm" onclick="editGoal('${g.id}')">Editar</button><button class="btn sm danger" onclick="delGoal('${g.id}')">Excluir</button></div></div></div>`}).join(''):'<div class="empty-state"><div class="empty-icon">🎯</div><h3>Crie uma meta</h3><p>Dê um destino ao dinheiro que você quer juntar e acompanhe o progresso.</p><button class="btn primary" onclick="openM(\'goal\')">+ Nova meta</button></div>')}
function editGoal(x){let g=data.goals.find(v=>v.id===x);if(!g)return;gName.value=g.name;gTarget.value=g.target;gSaved.value=g.saved;gMonthly.value=g.monthly;gDate.value=g.date||'';window.editingGoalId=x;document.querySelector('#mGoal h2').textContent='Editar meta';document.querySelector('#mGoal .btn.primary').textContent='Salvar alterações';document.querySelector('#mGoal .btn.primary').onclick=saveGoalEdit;openM('goal')}
function saveGoalEdit(){let g=data.goals.find(v=>v.id===window.editingGoalId);if(!g)return;let name=gName.value.trim(),target=n(gTarget.value);if(!name||target<=0)return toast('Informe meta e valor.',true);g.name=name;g.target=target;g.saved=n(gSaved.value);g.monthly=n(gMonthly.value);g.date=gDate.value;window.editingGoalId=null;document.querySelector('#mGoal h2').textContent='Nova meta';document.querySelector('#mGoal .btn.primary').textContent='Salvar meta';document.querySelector('#mGoal .btn.primary').onclick=saveGoal;logActivity('goal','Meta atualizada',g.name,g.target);save();closeM('goal');toast('✓ Meta atualizada')}
function totalVaults(){return (data.vaults||[]).reduce((sum,v)=>sum+(v.transactions||[]).reduce((a,t)=>a+(t.type==='withdraw'?-n(t.amount):n(t.amount)),0),0)}
function vaultBalance(v){return (v.transactions||[]).reduce((a,t)=>a+(t.type==='withdraw'?-n(t.amount):n(t.amount)),0)}
let editingVaultId=null,currentVaultTxId=null;
function openVaultEditor(x){let v=data.vaults.find(z=>z.id===x);if(!v)return;editingVaultId=x;vName.value=v.name;vCategory.value=v.category||'Outros';vInitial.value='';vaultModalTitle.textContent='Editar cofre';vaultSaveBtn.textContent='Salvar alterações';openM('vault')}
function saveVault(){let name=vName.value.trim();if(!name)return toast('Informe o nome do cofre.',true);let category=vCategory.value;if(editingVaultId){let v=data.vaults.find(z=>z.id===editingVaultId);if(v){v.name=name;v.category=category}}else{let initial=n(vInitial.value);let v={id:id(),name,category,transactions:[]};if(initial>0)v.transactions.push({id:id(),type:'deposit',amount:initial,desc:'Saldo inicial',date:new Date().toISOString().slice(0,10)});data.vaults.push(v)}logActivity('vault',editingVaultId?'Cofre atualizado':'Novo cofre',name,n(vInitial.value));editingVaultId=null;vaultModalTitle.textContent='Novo cofre';vaultSaveBtn.textContent='Criar cofre';save();closeM('vault');toast('✓ Cofre salvo')}
function openVaultTx(x,type='deposit'){currentVaultTxId=x;vTxType.value=type;vTxAmount.value='';vTxDesc.value='';vaultTxTitle.textContent=type==='withdraw'?'Retirar do cofre':'Depositar no cofre';openM('vaultTx')}
function saveVaultTx(){let v=data.vaults.find(z=>z.id===currentVaultTxId),amount=n(vTxAmount.value),type=vTxType.value;if(!v||amount<=0)return toast('Informe um valor válido.',true);if(type==='withdraw'&&amount>vaultBalance(v))return toast('A retirada é maior que o saldo do cofre.',true);v.transactions.push({id:id(),type,amount,desc:vTxDesc.value.trim()|| (type==='deposit'?'Depósito':'Retirada'),date:new Date().toISOString().slice(0,10)});logActivity('vault',type==='deposit'?'Depósito no cofre':'Retirada do cofre',v.name,type==='deposit'?amount:-amount);save();closeM('vaultTx');toast(type==='deposit'?'✓ Depósito registrado':'✓ Retirada registrada')}
function delVault(x){let v=data.vaults.find(z=>z.id===x);if(!v)return;if(confirm('Excluir este cofre e todo o histórico de movimentações?')){data.vaults=data.vaults.filter(z=>z.id!==x);save()}}
function renderVaults(){let list=document.getElementById('vaultList');if(!list)return;let total=totalVaults();vaultTotal.textContent=money(total);vaultCount.textContent=data.vaults.length;vaultGoalsRef.textContent=money(data.goals.reduce((s,g)=>s+n(g.saved),0));list.innerHTML=data.vaults.length?data.vaults.map(v=>{let bal=vaultBalance(v),tx=(v.transactions||[]).slice().reverse().slice(0,4);return `<div class="card vault-card"><div class="eyebrow">${esc(v.category||'Outros')}</div><h2>🔐 ${esc(v.name)}</h2><div class="vault-balance ${bal<0?'bad':'ok'}">${money(bal)}</div><div class="vault-actions"><button class="btn sm primary" onclick="openVaultTx('${v.id}','deposit')">+ Depositar</button><button class="btn sm" onclick="openVaultTx('${v.id}','withdraw')">− Retirar</button><button class="btn sm" onclick="openVaultEditor('${v.id}')">Editar</button><button class="btn sm danger" onclick="delVault('${v.id}')">Excluir</button></div><div class="vault-history">${tx.length?tx.map(t=>`<div class="vault-tx"><span>${t.type==='deposit'?'↗':'↘'} ${esc(t.desc)}<br><small class="muted">${t.date?new Date(t.date+'T12:00').toLocaleDateString('pt-BR'):'—'}</small></span><b class="${t.type==='deposit'?'positive':'negative'}">${t.type==='deposit'?'+':'−'} ${money(t.amount)}</b></div>`).join(''):'<div class="muted" style="margin-top:12px">Sem movimentações.</div>'}</div></div>`}).join(''):'<div class="empty-state" style="grid-column:1/-1"><div class="empty-icon">🔐</div><h3>Crie seu primeiro cofre</h3><p>Separe um valor para emergência ou qualquer reserva sem misturar com suas metas.</p><button class="btn primary" onclick="openM(\'vault\')">+ Novo cofre</button></div>'}
function chart(id,c){try{if(!window.Chart)return;if(charts[id])charts[id].destroy();charts[id]=new Chart(document.getElementById(id),c)}catch(e){console.warn(e)}}function renderDash(){let inc=incomeTotal(),ex=expenseTotal(),av=inc-ex,p=inc?Math.min(100,ex/inc*100):0;dIncome.textContent=money(inc);dCommit.textContent=money(ex);dAvail.textContent=money(av);dAvail.className='value '+(av<0?'bad':'ok');let goalTargetTotal=data.goals.reduce((s,g)=>s+n(g.target),0),goalSavedTotal=data.goals.reduce((s,g)=>s+n(g.saved),0),vaultTotal=totalVaults();dReserveGoals.textContent=money(goalTargetTotal);dReserveGoalsSub.textContent='Depositado: '+money(goalSavedTotal);dReserveVault.textContent=money(vaultTotal);pct.textContent=p.toFixed(1)+'%';let cats={};data.expenses.forEach(e=>{let v=expMonth(e);if(v)cats[e.category]=(cats[e.category]||0)+v});chart('donut',{type:'doughnut',data:{labels:['Comprometido','Livre'],datasets:[{data:[ex,Math.max(0,inc-ex)]}]},options:{cutout:'70%',maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});chart('cats',{type:'doughnut',data:{labels:Object.keys(cats).length?Object.keys(cats):['Sem gastos'],datasets:[{data:Object.values(cats).length?Object.values(cats):[1]}]},options:{maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});let level=p<50?'🟢 Orçamento confortável':p<75?'🟡 Atenção aos compromissos':'🔴 Alta concentração de renda';health.innerHTML=`<h2>${level}</h2><p class="muted">${p.toFixed(1)}% da renda líquida estimada está comprometida neste mês.</p>`;upcoming.innerHTML=data.expenses.slice().sort((a,b)=>String(a.due).localeCompare(String(b.due))).slice(0,6).map(e=>`<div class="row"><span>${esc(e.name)}<br><small class="muted">${e.due?new Date(e.due+'T12:00').toLocaleDateString('pt-BR'):'—'}</small></span><b>${money(expMonth(e))}</b></div>`).join('')||'<div class="empty">Nada por aqui.</div>'}


/* ========================================================= JAVASCRIPT — DASHBOARD / GUIA ========================================================= */
function renderDashboardGuide(){
  const el=document.getElementById('dashboardGuide');if(!el)return;
  const missing=[];
  if(!data.incomeSources.length)missing.push(['💰','Renda','income']);
  if(!data.expenses.length)missing.push(['💸','Gastos','expenses']);
  if(!data.goals.length)missing.push(['🎯','Metas','planning']);
  if(!data.vaults.length)missing.push(['🔐','Cofre','vaults']);
  if(!missing.length){el.innerHTML='';return}
  el.innerHTML=`<div class="setup-guide"><div><div class="eyebrow">Complete seu FinanSee</div><h2>Falta pouco para deixar tudo redondo.</h2><p class="muted">Você pode completar estes itens quando quiser.</p></div><div class="setup-chips">${missing.map(([icon,label,page])=>`<button onclick="go('${page}')">${icon} ${label}</button>`).join('')}</div></div>`;
}
const renderDashGuideBase=renderDash;
renderDash=function(){renderDashGuideBase();renderDashboardGuide()};
