/* ========================================================= JAVASCRIPT — PWA / PRIMEIRO ACESSO / INSTALAÇÃO ========================================================= */
let deferredInstallPrompt=null;const INSTALL_INTRO_KEY='finansee_install_intro_v8';
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;renderPwaStatus();renderInstallIntro()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;localStorage.setItem(INSTALL_INTRO_KEY,'done');hideInstallIntro();renderPwaStatus();toast('✓ FinanSee instalado')});
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function shouldShowInstallIntro(){return !isStandalone()&&!localStorage.getItem(INSTALL_INTRO_KEY)}
function hideInstallIntro(){document.getElementById('installIntroScreen')?.classList.remove('show')}
function continueInBrowser(){localStorage.setItem(INSTALL_INTRO_KEY,'browser');hideInstallIntro()}
async function installFromIntro(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;localStorage.setItem(INSTALL_INTRO_KEY,'done');hideInstallIntro();renderPwaStatus();return}const hint=document.getElementById('installIntroHint');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){if(hint)hint.textContent='No Safari: toque em Compartilhar → Adicionar à Tela de Início.'}else{if(hint)hint.textContent='Seu navegador ainda não liberou o botão automático. Use o menu → Instalar app / Adicionar à tela inicial.'}}
function renderInstallIntro(){const screen=document.getElementById('installIntroScreen'),btn=document.getElementById('introInstallBtn'),hint=document.getElementById('installIntroHint');if(!screen)return;if(!shouldShowInstallIntro()){screen.classList.remove('show');return}screen.classList.add('show');const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);if(btn)btn.textContent=deferredInstallPrompt?'Instalar FinanSee':ios?'Como instalar no iPhone':'Instalar FinanSee';if(hint)hint.textContent=deferredInstallPrompt?'Instalação disponível neste navegador.':ios?'No iPhone, o Safari usa Compartilhar → Adicionar à Tela de Início.':'Se a instalação automática ainda não estiver disponível, você pode continuar no navegador.'}
async function installPwa(){if(isStandalone())return toast('O FinanSee já está aberto como aplicativo.');if(!deferredInstallPrompt){const msg=/iPhone|iPad|iPod/i.test(navigator.userAgent)?'No Safari, use Compartilhar → Adicionar à Tela de Início.':'Abra o menu do navegador e escolha “Instalar app” ou “Adicionar à tela inicial”.';return toast(msg,true)}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;renderPwaStatus()}
function renderPwaStatus(){const status=document.getElementById('pwaStatus'),btn=document.getElementById('installPwaBtn'),top=document.getElementById('installTopBtn'),standalone=isStandalone();if(status)status.innerHTML=standalone?'<span class="status-dot ok-dot"></span> Instalado / modo aplicativo':(window.isSecureContext?'<span class="status-dot warn-dot"></span> Pronto para instalar quando o navegador oferecer':'<span class="status-dot"></span> PWA exige HTTPS ou localhost');if(btn){btn.style.display=standalone?'none':'inline-flex';btn.disabled=!window.isSecureContext}if(top)top.style.display=!standalone&&deferredInstallPrompt?'inline-flex':'none'}
async function registerServiceWorker(){if(!('serviceWorker' in navigator)||!window.isSecureContext)return renderPwaStatus();try{const reg=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});await reg.update();reg.addEventListener('updatefound',()=>{const w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('Nova versão disponível. Feche e abra o app para atualizar.')})})}catch(e){console.warn('Service Worker:',e)}finally{renderPwaStatus()}}
function updateOnlineStatus(){const el=document.getElementById('offlineBanner');if(el)el.classList.toggle('show',!navigator.onLine)}window.addEventListener('online',()=>{updateOnlineStatus();toast('✓ Conexão restaurada')});window.addEventListener('offline',updateOnlineStatus);window.addEventListener('DOMContentLoaded',()=>{updateOnlineStatus();setTimeout(renderInstallIntro,80)});
