/* ========================================================= JAVASCRIPT — SEGURANÇA LOCAL (SENHA / PIN) ========================================================= */
function securityStorageKey(){return typeof userSecurityKey==='function'?userSecurityKey():'finansee_security_guest'}
let securityTimer=null;let hiddenAt=0;
function getSecurity(){try{return JSON.parse(localStorage.getItem(securityStorageKey())||'null')}catch(e){return null}}
function bytesToB64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function deriveSecret(secret,saltB64,iterations=150000){if(!crypto?.subtle)throw new Error('Web Crypto indisponível neste navegador.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:b64urlToBytes(saltB64),iterations,hash:'SHA-256'},key,256);return bytesToB64url(bits)}
function randomB64(size=16){const b=new Uint8Array(size);crypto.getRandomValues(b);return bytesToB64url(b)}
function constantTimeEqual(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function saveLocalPassword(){const p=document.getElementById('securityNew')?.value||'',c=document.getElementById('securityConfirm')?.value||'',minutes=Number(document.getElementById('securityTimeout')?.value||5);if(p.length<4)return toast('Use pelo menos 4 caracteres.',true);if(p!==c)return toast('A confirmação não confere.',true);try{const salt=randomB64(16),iterations=150000,hash=await deriveSecret(p,salt,iterations);localStorage.setItem(securityStorageKey(),JSON.stringify({enabled:true,salt,hash,iterations,autoLockMinutes:minutes}));document.getElementById('securityNew').value='';document.getElementById('securityConfirm').value='';sessionStorage.setItem('finansee_unlocked','1');renderSecuritySettings();resetSecurityTimer();toast('✓ Senha/PIN local configurado')}catch(e){toast(e.message||'Não foi possível configurar a segurança.',true)}}
function updateSecurityTimeout(){const s=getSecurity();if(!s?.enabled)return;s.autoLockMinutes=Number(document.getElementById('securityTimeout')?.value||5);localStorage.setItem(securityStorageKey(),JSON.stringify(s));resetSecurityTimer();toast('✓ Tempo de bloqueio atualizado')}
function disableLocalSecurity(){if(!confirm('Desativar o bloqueio por senha/PIN deste dispositivo?'))return;localStorage.removeItem(securityStorageKey());sessionStorage.removeItem('finansee_unlocked');hideLockScreen();renderSecuritySettings();toast('Bloqueio local desativado')}
function lockApp(){const s=getSecurity();if(!s?.enabled)return;sessionStorage.removeItem('finansee_unlocked');document.body.classList.add('app-locked');document.getElementById('lockScreen')?.classList.add('show');const input=document.getElementById('unlockSecret');if(input){input.value='';setTimeout(()=>input.focus(),100)}}
function hideLockScreen(){document.body.classList.remove('app-locked');document.getElementById('lockScreen')?.classList.remove('show');sessionStorage.setItem('finansee_unlocked','1');resetSecurityTimer()}
async function unlockApp(){const s=getSecurity();if(!s?.enabled)return hideLockScreen();const secret=document.getElementById('unlockSecret')?.value||'';if(!secret)return;try{const hash=await deriveSecret(secret,s.salt,s.iterations||150000);if(!constantTimeEqual(hash,s.hash))return setUnlockMessage('Senha/PIN incorreto.');hideLockScreen();setUnlockMessage('')}catch(e){setUnlockMessage(e.message||'Falha ao desbloquear.')}}
function setUnlockMessage(t){const el=document.getElementById('unlockMessage');if(el)el.textContent=t}
function resetSecurityTimer(){clearTimeout(securityTimer);const s=getSecurity();if(!s?.enabled||document.body.classList.contains('app-locked'))return;const m=Number(s.autoLockMinutes??5);if(m<=0)return;securityTimer=setTimeout(lockApp,m*60*1000)}
function activityPing(){if(!document.body.classList.contains('app-locked'))resetSecurityTimer()}
function renderSecuritySettings(){const s=getSecurity(),status=document.getElementById('securityStatus'),timeout=document.getElementById('securityTimeout'),dis=document.getElementById('securityDisableBtn');if(status)status.innerHTML=s?.enabled?'<span class="status-dot ok-dot"></span> Proteção local ativa':'<span class="status-dot"></span> Proteção local desativada';if(timeout)timeout.value=String(s?.autoLockMinutes??5);if(dis)dis.style.display=s?.enabled?'inline-flex':'none'}
function initializeSecurityGate(){document.body.classList.remove('security-checking');const s=getSecurity();if(s?.enabled)lockApp();else hideLockScreen();['pointerdown','keydown','touchstart'].forEach(ev=>window.addEventListener(ev,activityPing,{passive:true}));document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenAt=Date.now();return}const cfg=getSecurity();if(!cfg?.enabled)return;const mins=Number(cfg.autoLockMinutes??5);if(mins===0||Date.now()-hiddenAt>=mins*60*1000)lockApp();else resetSecurityTimer()});document.getElementById('unlockSecret')?.addEventListener('keydown',e=>{if(e.key==='Enter')unlockApp()})}
