/* ========================================================= JAVASCRIPT — CONFIGURAÇÕES / BACKUP / APARÊNCIA ========================================================= */
function saveCfg(){data.profile.name=cfgName.value.trim();data.profile.closeDay=Number(cfgClose.value)||22;data.profile.state=String(document.getElementById('cfgState')?.value||'').trim().toUpperCase().slice(0,2);data.profile.city=String(document.getElementById('cfgCity')?.value||'').trim();const users=getUsers(),idx=users.findIndex(u=>u.id===currentUserId());if(idx>=0&&data.profile.name){users[idx].name=data.profile.name;setUsers(users);currentUser=users[idx]}logActivity('profile','Perfil atualizado');save();renderAccountSettings();toast('✓ Configurações salvas')}
function renderCfg(){cfgName.value=data.profile.name||currentUser?.name||'';cfgClose.value=data.profile.closeDay||22;const st=document.getElementById('cfgState'),ct=document.getElementById('cfgCity');if(st)st.value=data.profile.state||'';if(ct)ct.value=data.profile.city||'';if(typeof renderSecuritySettings==='function')renderSecuritySettings();if(typeof renderPwaStatus==='function')renderPwaStatus();if(typeof renderAccountSettings==='function')renderAccountSettings();renderThemeChoice()}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='finansee-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);logActivity('backup','Backup exportado');save()}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{const imported=JSON.parse(r.result);if(!imported||typeof imported!=='object')throw new Error();data=normalizeData(imported);if(data.incomeSources.length)data.profile.onboardingCompleted=true;logActivity('backup','Backup importado',f.name);save();toast('✓ Backup importado para esta conta')}catch(x){toast('Backup JSON inválido',true)}finally{e.target.value=''}};r.readAsText(f)}
function resetData(){if(!confirm('Limpar todos os dados financeiros desta conta? A conta e a senha continuarão existindo.'))return;const token=prompt('Digite LIMPAR para confirmar:');if(token!=='LIMPAR')return toast('Limpeza cancelada');data=emptyData(currentUser?.name||'');localStorage.setItem(userDataKey(),JSON.stringify(data));renderAll();showOnboarding?.(1);toast('Dados financeiros zerados')}
const THEME_KEY='finansee_theme_mode_v8';
function resolvedTheme(mode){if(mode==='dark'||mode==='light')return mode;return window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
function applyThemeMode(mode='system'){const actual=resolvedTheme(mode);const dark=actual==='dark';document.documentElement.classList.toggle('dark',dark);document.body.classList.toggle('dark',dark);document.documentElement.dataset.themeMode=mode;const icon=document.getElementById('themeIcon');if(icon)icon.textContent=dark?'☀':'☾';renderThemeChoice()}
function applyStoredTheme(){applyThemeMode(localStorage.getItem(THEME_KEY)||'system')}
function setThemeMode(mode){if(!['system','light','dark'].includes(mode))mode='system';localStorage.setItem(THEME_KEY,mode);applyThemeMode(mode);toast('✓ Aparência atualizada')}
function toggleTheme(){const dark=document.documentElement.classList.contains('dark');setThemeMode(dark?'light':'dark')}
function renderThemeChoice(){const mode=localStorage.getItem(THEME_KEY)||'system';document.querySelectorAll('[data-theme-mode]').forEach(b=>b.classList.toggle('active',b.dataset.themeMode===mode))}
if(window.matchMedia){const mq=window.matchMedia('(prefers-color-scheme: dark)');mq.addEventListener?.('change',()=>{if((localStorage.getItem(THEME_KEY)||'system')==='system')applyThemeMode('system')})}
