/* ========================================================= JAVASCRIPT — VALE ALIMENTAÇÃO ========================================================= */
function vaMonth(key=selectedMonthKey()){const va=data.profile.va||(data.profile.va={expected:0,monthly:{},transactions:[]});va.monthly=va.monthly||{};va.transactions=va.transactions||[];return va.monthly[key]||(va.monthly[key]={deposited:0})}
function vaSpentTotal(key=selectedMonthKey()){return (data.profile.va?.transactions||[]).filter(t=>String(t.date||'').slice(0,7)===key).reduce((s,t)=>s+n(t.amount),0)}
function vaStats(key=selectedMonthKey()){const expected=n(data.profile.va?.monthly?.[key]?.expected ?? data.profile.va?.expected),deposited=n(data.profile.va?.monthly?.[key]?.deposited),spent=vaSpentTotal(key),remaining=Math.max(0,deposited-spent);return{expected,deposited,spent,remaining}}
function openVaConfig(){vaConfigExpected.value=data.profile.va?.expected?money(data.profile.va.expected):'';openM('vaConfig')}
function saveVaConfig(){data.profile.va=data.profile.va||{expected:0,monthly:{},transactions:[]};data.profile.va.expected=n(vaConfigExpected.value);data.profile.va.monthly=data.profile.va.monthly||{};data.profile.va.monthly[selectedMonthKey()]={...(data.profile.va.monthly[selectedMonthKey()]||{}),expected:data.profile.va.expected};logActivity('va','VA configurado','Valor mensal previsto',data.profile.va.expected);save();closeM('vaConfig');toast('✓ Vale Alimentação atualizado')}
function registerVaDeposit(){const key=selectedMonthKey(),current=n(data.profile.va?.monthly?.[key]?.deposited),val=prompt(`Quanto foi depositado de VA em ${monthLabel(key)}?`,current?String(current).replace('.',','):'');if(val===null)return;const amount=n(val);if(amount<0)return toast('Valor inválido.',true);data.profile.va=data.profile.va||{expected:0,monthly:{},transactions:[]};data.profile.va.monthly=data.profile.va.monthly||{};data.profile.va.monthly[key]={...(data.profile.va.monthly[key]||{}),expected:n(data.profile.va.monthly[key]?.expected ?? data.profile.va.expected),deposited:amount,date:new Date().toISOString().slice(0,10)};logActivity('va','VA depositado',monthLabel(key),amount);save();toast('✓ Depósito de VA registrado')}
function openVaSpend(){const [y,m]=selectedMonthKey().split('-').map(Number),today=new Date();vaSpendDate.value=(today.getFullYear()===y&&today.getMonth()+1===m)?today.toISOString().slice(0,10):`${selectedMonthKey()}-01`;vaSpendAmount.value='';vaSpendCategory.value='Mercado';vaSpendDesc.value='';vaSpendOther.value='';vaCategoryUI();openM('vaSpend')}
function vaCategoryUI(){vaOtherWrap.style.display=vaSpendCategory.value==='Outros'?'grid':'none'}
function saveVaSpend(){const amount=n(vaSpendAmount.value),date=vaSpendDate.value,category=vaSpendCategory.value,desc=vaSpendCategory.value==='Outros'?(vaSpendOther.value.trim()||vaSpendDesc.value.trim()):vaSpendDesc.value.trim();if(amount<=0||!date)return toast('Informe data e valor.',true);if(String(date).slice(0,7)!==selectedMonthKey())return toast('A data precisa pertencer à competência selecionada.',true);data.profile.va=data.profile.va||{expected:0,monthly:{},transactions:[]};data.profile.va.transactions=data.profile.va.transactions||[];data.profile.va.transactions.push({id:id(),date,amount,category,desc});logActivity('va','Gasto no VA',`${category}${desc?' · '+desc:''}`,amount);save();closeM('vaSpend');toast('✓ Gasto do VA registrado')}
function delVaTx(txid){if(!confirm('Excluir esta movimentação do VA?'))return;data.profile.va.transactions=(data.profile.va.transactions||[]).filter(t=>t.id!==txid);save()}
function renderVa(){const key=selectedMonthKey(),st=vaStats(key);if(document.getElementById('vaExpected'))vaExpected.textContent=money(st.expected);if(document.getElementById('vaDeposited'))vaDeposited.textContent=money(st.deposited);if(document.getElementById('vaSpent'))vaSpent.textContent=money(st.spent);if(document.getElementById('vaRemaining'))vaRemaining.textContent=money(st.remaining);if(document.getElementById('dVaRemaining'))dVaRemaining.textContent=money(st.remaining);if(document.getElementById('dVaSub'))dVaSub.textContent='Depositado: '+money(st.deposited);
 const el=document.getElementById('vaTransactions');if(!el)return;const tx=(data.profile.va?.transactions||[]).filter(t=>String(t.date||'').slice(0,7)===key).sort((a,b)=>String(b.date).localeCompare(String(a.date)));el.innerHTML=tx.length?tx.map(t=>`<div class="row va-tx"><span><b>${esc(t.category)}</b><br><small class="muted">${new Date(t.date+'T12:00').toLocaleDateString('pt-BR')}${t.desc?' · '+esc(t.desc):''}</small></span><span><b class="bad">− ${money(t.amount)}</b> <button class="btn sm danger" onclick="delVaTx('${t.id}')">Excluir</button></span></div>`).join(''):'<div class="empty-state compact-empty"><h3>Nenhum gasto de VA neste mês</h3><p>Registre as compras feitas com o benefício para acompanhar o saldo restante.</p></div>'}
